colormsg("")
colormsg(HICYAN "jni")

if(META_PROJECT MATCHES "^simulation")
  find_package(JNI REQUIRED QUIET)
  find_package(Java REQUIRED QUIET)
else(META_PROJECT MATCHES "^simulation")
  find_package(JNI QUIET)
  find_package(Java QUIET)
endif(META_PROJECT MATCHES "^simulation")

REPORT_FIND(jni JNI_INCLUDE_DIRS ${JNI_INCLUDE_DIRS})
REPORT_FIND(jni JNI_LIBRARIES ${JNI_LIBRARIES})

IF(NOT IS_DIRECTORY $ENV{JAVA_HOME})
  FOUND_NOT_OK("JAVA_HOME ($ENV{JAVA_HOME}) is either unset or does not point to a valid directory.")
  FOUND_NOT_OK("This is only an error if some project in your workspace requires java.")
  if(META_PROJECT MATCHES "^simulation")
    message(FATAL_ERROR "But ${META_PROJECT} uses JAVA_HOME, so we're stopping hard.")
  endif(META_PROJECT MATCHES "^simulation")
ELSE(NOT IS_DIRECTORY $ENV{JAVA_HOME})
  FOUND_OK("JAVA_HOME=$ENV{JAVA_HOME}")
ENDIF(NOT IS_DIRECTORY $ENV{JAVA_HOME})