#!/bin/bash

# SPDX-FileCopyrightText: 2024 The IceTray Contributors
#
# SPDX-License-Identifier: BSD-2-Clause

set -e

if [ $# -lt 3 ]; then
    echo "usage: icetray-stubgen SRC_DIR BUILD_DIR module [module...]" >&2
    exit 1
fi
SRC_DIR=$1
shift 1
BUILD_DIR=$1
shift 1

cd $BUILD_DIR
rm -r $SRC_DIR/stubs/icecube/* || true
$BUILD_DIR/env-shell.sh pybind11-stubgen --config $SRC_DIR/pyproject.toml -o $SRC_DIR/stubs --root-module-suffix "" --no-setup-py \
   -i icecube.dataclasses -i icecube.phys_services -i icecube.simclasses -i icecube.recclasses -i icecube.sim_services -i icecube.tableio \
   $@
ruff check --isolated --select PYI013,PYI029,PYI011,PYI018,I001,F401 --fix $SRC_DIR/stubs
ruff format --isolated $SRC_DIR/stubs
