#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2024 The IceTray Contributors
#
# SPDX-License-Identifier: BSD-2-Clause

import os
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
import subprocess
import shutil

try:
    src = Path(os.environ["I3_SRC"])
except:
    sys.stderr.write("I3_SRC is not set, doing nothing\n")
    sys.exit(-1)

tempdir = TemporaryDirectory()

whitelist_files = [
    "CODEOWNERS",
    "CONTRIBUTING.rst",
    "Brewfile",
    "pyproject.toml",
    ".editorconfig",
    "requirements.txt",
    ".gitignore",
    ".pre-commit-config.yaml",
    "neutrino-generator/private/neutrino-generator/Step.h",
    "neutrino-generator/private/pybindings/TypeDefs.cxx",
    "neutrino-generator/private/pybindings/Steering.cxx",
    "neutrino-generator/private/pybindings/Interaction.cxx",
    "neutrino-generator/private/pybindings/ZenithSampler.cxx",
    "clsim/CMakeLists.txt",
    "clsim/private/clsim/I3CLSimLightSourceToStepConverterFlasher.cxx",
    "clsim/private/clsim/I3CLSimLightSourceToStepConverterPPC.cxx",
    "clsim/private/clsim/I3CLSimLightSourceToStepConverterUtils.cxx",
    "clsim/private/clsim/I3CLSimLightSourceToStepConverterUtils.h",
    "clsim/private/clsim/I3CLSimModule.cxx",
    "clsim/private/clsim/I3CLSimModuleHelper.cxx",
    "clsim/private/clsim/I3CLSimSpectrumTable.cxx",
    "clsim/private/clsim/converter/I3MCHitConverterWithIDs.cxx",
    "clsim/private/clsim/converter/I3MCHitConverterWithIDs.h",
    "clsim/private/clsim/dom/I3PhotonToMCHitConverterForMultiPMT.cxx",
    "clsim/private/clsim/opencl.hpp",
    "clsim/private/clsim/shadow/I3ShadowedPhotonRemoverModule.cxx",
    "clsim/private/clsim/tabulator/Axes.cxx",
    "clsim/private/clsim/tabulator/Axes.h",
    "clsim/private/clsim/tabulator/Axis.cxx",
    "clsim/private/clsim/tabulator/Axis.h",
    "clsim/private/clsim/tabulator/I3CLSimStepToTableConverter.cxx",
    "clsim/private/clsim/tabulator/I3CLSimStepToTableConverter.h",
    "clsim/private/clsim/tabulator/I3CLSimTabulatorModule.cxx",
    "clsim/private/clsim/util/I3MuonSliceRemoverAndPulseRelabeler.cxx",
    "clsim/private/clsim/util/I3MuonSlicer.cxx",
    "clsim/private/clsim/util/I3TauSanitizer.cxx",
    "clsim/private/cuda/I3CLSimStepToPhotonConverterCUDA.cxx",
    "clsim/private/cuda/I3CLSimStepToPhotonConverterCUDA.h",
    "clsim/private/cuda/kernels/CMakeLists.txt",
    "clsim/private/cuda/kernels/dataStructCuda.cuh",
    "clsim/private/cuda/kernels/domGeoData.cuh",
    "clsim/private/cuda/kernels/helper_math.h",
    "clsim/private/cuda/kernels/propagationKernelFunctions.cuh",
    "clsim/private/cuda/kernels/propagationKernelSource.cu",
    "clsim/private/cuda/kernels/propagationKernelSource.cuh",
    "clsim/private/cuda/kernels/rng.cuh",
    "clsim/private/cuda/kernels/scatteringAndAbsorbtionData.cuh",
    "clsim/private/cuda/kernels/settings.cuh",
    "clsim/private/cuda/kernels/utils.cuh",
    "clsim/private/cuda/kernels/wlenBiasSource.cuh",
    "clsim/private/cuda/kernels/wlenGeneration.cuh",
    "clsim/private/cuda/kernels/zOffsetHandling.cuh",
    "clsim/private/geant4/I3CLSimI3ParticleGeantConverter.hh",
    "clsim/private/geant4/I3CLSimLightSourcePropagatorGeant4.cxx",
    "clsim/private/geant4/I3CLSimLightSourcePropagatorGeant4.h",
    "clsim/private/geant4/TrkCerenkov.cxx",
    "clsim/private/geant4/TrkCerenkov.hh",
    "clsim/private/geant4/TrkDetectorConstruction.cxx",
    "clsim/private/geant4/TrkDetectorConstruction.hh",
    "clsim/private/geant4/TrkEventAction.cxx",
    "clsim/private/geant4/TrkEventAction.hh",
    "clsim/private/geant4/TrkOpticalPhysics.cxx",
    "clsim/private/geant4/TrkOpticalPhysics.hh",
    "clsim/private/geant4/TrkPrimaryGeneratorAction.cxx",
    "clsim/private/geant4/TrkPrimaryGeneratorAction.hh",
    "clsim/private/geant4/TrkStackingAction.cxx",
    "clsim/private/geant4/TrkStackingAction.hh",
    "clsim/private/geant4/TrkUISessionToQueue.cxx",
    "clsim/private/geant4/TrkUISessionToQueue.hh",
    "clsim/private/geant4/TrkUserEventInformation.cxx",
    "clsim/private/geant4/TrkUserEventInformation.hh",
    "clsim/private/opencl/I3CLSimHelperGenerateGeometrySource.cxx",
    "clsim/private/opencl/I3CLSimHelperGenerateGeometrySource.h",
    "clsim/private/opencl/I3CLSimHelperGenerateMediumPropertiesSource.cxx",
    "clsim/private/opencl/I3CLSimHelperGenerateMediumPropertiesSource.h",
    "clsim/private/opencl/I3CLSimHelperGenerateMediumPropertiesSource_Optimizers.cxx",
    "clsim/private/opencl/I3CLSimHelperGenerateMediumPropertiesSource_Optimizers.h",
    "clsim/private/opencl/I3CLSimHelperLoadProgramSource.h",
    "clsim/private/opencl/I3CLSimOpenCLDevice.cxx",
    "clsim/private/opencl/I3CLSimStepToPhotonConverterOpenCL.cxx",
    "clsim/private/opencl/ieeehalfprecision.cxx",
    "clsim/private/pybindings/I3CLSimLightSourcePropagatorGeant4.cxx",
    "clsim/private/pybindings/I3CLSimLightSourceToStepConverter.cxx",
    "clsim/private/pybindings/I3CLSimLightSourceToStepConverterUtils.cxx",
    "clsim/private/pybindings/I3CLSimModuleHelper.cxx",
    "clsim/private/pybindings/I3CLSimOpenCLDevice.cxx",
    "clsim/private/pybindings/I3CLSimSpectrumTable.cxx",
    "clsim/private/pybindings/I3CLSimStepToPhotonConverterOpenCL.cxx",
    "clsim/private/pybindings/I3CLSimTester.cxx",
    "clsim/private/pybindings/module.cxx",
    "clsim/private/pybindings/tabulator.cxx",
    "clsim/private/test/I3CLSimFunctionTester.cxx",
    "clsim/private/test/I3CLSimFunctionTester.h",
    "clsim/private/test/I3CLSimMediumPropertiesTester.cxx",
    "clsim/private/test/I3CLSimMediumPropertiesTester.h",
    "clsim/private/test/I3CLSimRandomDistributionTester.cxx",
    "clsim/private/test/I3CLSimRandomDistributionTester.h",
    "clsim/private/test/I3CLSimRandomNumberGeneratorBenchmark.cxx",
    "clsim/private/test/I3CLSimRandomNumberGeneratorBenchmark.h",
    "clsim/private/test/I3CLSimScalarFieldTester.cxx",
    "clsim/private/test/I3CLSimScalarFieldTester.h",
    "clsim/private/test/I3CLSimTesterBase.cxx",
    "clsim/private/test/I3CLSimTesterBase.h",
    "clsim/private/test/I3CLSimVectorTransformTester.cxx",
    "clsim/private/test/I3CLSimVectorTransformTester.h",
    "clsim/public/clsim/I3CLSimLightSourceToStepConverterFlasher.h",
    "clsim/public/clsim/I3CLSimLightSourceToStepConverterPPC.h",
    "clsim/public/clsim/I3CLSimModule.h",
    "clsim/public/clsim/I3CLSimModuleHelper.h",
    "clsim/public/clsim/I3CLSimOpenCLDevice.h",
    "clsim/public/clsim/I3CLSimSpectrumTable.h",
    "clsim/public/clsim/I3CLSimStepToPhotonConverterOpenCL.h",
    "clsim/public/clsim/dom/I3PhotonToMCHitConverterForMultiPMT.h",
    "clsim/public/clsim/shadow/I3ShadowedPhotonRemoverModule.h",
    "clsim/public/clsim/util/I3MuonSlicer.h",
    "clsim/python/AsyncTap.py",
    "clsim/python/FakeFlasherInfoGenerator.py",
    "clsim/python/FlasherInfoVectToFlasherPulseSeriesConverter.py",
    "clsim/python/GetAntaresOMAcceptance.py",
    "clsim/python/GetAntaresOMAngularSensitivity.py",
    "clsim/python/GetDefaultParameterizationList.py",
    "clsim/python/GetFlasherParameterizationList.py",
    "clsim/python/GetHybridParameterizationList.py",
    "clsim/python/GetIceCubeDOMAcceptance.py",
    "clsim/python/GetIceCubeDOMAngularSensitivity.py",
    "clsim/python/GetIceCubeFlasherSpectrum.py",
    "clsim/python/GetKM3NeTDOMAcceptance.py",
    "clsim/python/I3CLSimRandomValueIceCubeFlasherTimeProfile.py",
    "clsim/python/MakeAntaresMediumProperties.py",
    "clsim/python/MakeIceCubeMediumProperties.py",
    "clsim/python/MakeIceCubeMediumPropertiesPhotonics.py",
    "clsim/python/StandardCandleFlasherPulseSeriesGenerator.py",
    "clsim/python/__init__.py",
    "clsim/python/tablemaker/tabulator.py",
    "clsim/python/traysegments/I3CLSimMakeHits.py",
    "clsim/python/traysegments/I3CLSimMakeHitsFromPhotons.py",
    "clsim/python/traysegments/I3CLSimMakePhotons.py",
    "clsim/python/traysegments/__init__.py",
    "clsim/python/util/GetAnisotropyTransforms.py",
    "clsim/python/util/GetIceTiltZShift.py",
    "clsim/python/util/GetRefractiveIndexRange.py",
    "clsim/python/util/__init__.py",
    "clsim/python/util/interpolate.py",
    "clsim/resources/docs/faq.rst",
    "clsim/resources/docs/index.rst",
    "clsim/resources/docs/overview.rst",
    "clsim/resources/docs/tabulator.rst",
    "clsim/resources/kernels/Random123/LICENSE",
    "clsim/resources/kernels/Random123/include/Random123/MicroURNG.hpp",
    "clsim/resources/kernels/Random123/include/Random123/ReinterpretCtr.hpp",
    "clsim/resources/kernels/Random123/include/Random123/aes.h",
    "clsim/resources/kernels/Random123/include/Random123/array.h",
    "clsim/resources/kernels/Random123/include/Random123/ars.h",
    "clsim/resources/kernels/Random123/include/Random123/conventional/Engine.hpp",
    "clsim/resources/kernels/Random123/include/Random123/conventional/gsl_cbrng.h",
    "clsim/resources/kernels/Random123/include/Random123/features/clangfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/compilerfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/gccfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/iccfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/msvcfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/nvccfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/open64features.h",
    "clsim/resources/kernels/Random123/include/Random123/features/openclfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/pgccfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/sse.h",
    "clsim/resources/kernels/Random123/include/Random123/features/sunprofeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/features/xlcfeatures.h",
    "clsim/resources/kernels/Random123/include/Random123/gsl_microrng.h",
    "clsim/resources/kernels/Random123/include/Random123/philox.h",
    "clsim/resources/kernels/Random123/include/Random123/threefry.h",
    "clsim/resources/kernels/cylindrical_coordinates.c.cl",
    "clsim/resources/kernels/medium_properties_test_kernel.c.cl",
    "clsim/resources/kernels/medium_properties_test_kernel.h.cl",
    "clsim/resources/kernels/propagation_kernel.c.cl",
    "clsim/resources/kernels/propagation_kernel.h.cl",
    "clsim/resources/kernels/scalar_field_test_kernel.c.cl",
    "clsim/resources/kernels/scalar_field_test_kernel.h.cl",
    "clsim/resources/kernels/sparse_collision_kernel.c.cl",
    "clsim/resources/kernels/sparse_collision_kernel.h.cl",
    "clsim/resources/kernels/spherical_coordinates.c.cl",
    "clsim/resources/kernels/vector_transform_test_kernel.c.cl",
    "clsim/resources/kernels/vector_transform_test_kernel.h.cl",
    "clsim/resources/kernels/wlen_dep_val_test_kernel.c.cl",
    "clsim/resources/kernels/wlen_dep_val_test_kernel.h.cl",
    "clsim/resources/tablemaker/photomc.py",
]

whitelist = [
    ".github",
    ".reuse",
    "astro",
    "cmake",
    "dataclasses",
    "dataio",
    "docs",
    "hdfwriter",
    "icetray",
    "interfaces",
    "LICENSES",
    "phys-services",
    "serialization",
    "steamshovel",
    "tableio",
]

ignore = shutil.ignore_patterns("*.pyc")

for x in whitelist_files:
    dest = Path(tempdir.name) / x
    os.makedirs(dest.parent, exist_ok=True)
    shutil.copy(src / x, dest)

for x in whitelist:
    shutil.copytree(src / x, Path(tempdir.name) / x, ignore=ignore)

ret = subprocess.run(["reuse", "lint"], cwd=tempdir.name, check=False)
print("reuse returned ", ret.returncode)
sys.exit(ret.returncode)
